Sveyko.B1RADIO/Models/Soundtrack.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sveyko.B1RADIO.Models
{
    public partial class Soundtrack
    {
        public int Id { get; set; }
        [Display(Name = "Genre")]
        [Required(ErrorMessage = "Genre is required")]
        public int GenreId { get; set; }
        [Display(Name = "Singer")]
        [Required(ErrorMessage = "Singer is required")]
        public int SingerId { get; set; }
        [Display(Name = "Title")]
        [Required(ErrorMessage = "Title is required")]
        [StringLength(150)]
        public string Title { get; set; }
        public string ServerFilename { get; set; }
        [Display(Name = "File name")]
        [Required(ErrorMessage = "File is required")]
        public string ClientFilename { get; set; }
        public Genre Genre { get; set; }
        public Singer Singer { get; set; }

        //[NotMapped]
        //public string CurrentSortOrder { get; set; }
        //[NotMapped]
        //public string CurrentFilter { get; set; }
        //[NotMapped]
        //public string CurrentSort { get; set; }
    }
}

Sveyko.B1RADIO/Controllers/SoundtracksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sveyko.B1RADIO.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System.IO;
using Sveyko.B1RADIO.Utils;

namespace Sveyko.B1RADIO.Controllers
{
    public class SoundtracksController : Controller
    {
        private readonly B1RADIOContext _context;

        private string TmpFileDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/soundtracks/temp");
        private string WorkFileDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/soundtracks");

        public SoundtracksController(B1RADIOContext context)
        {
            _context = context;
        }

        // GET: Soundtracks
        public async Task<IActionResult> Index(string sortOrder, int searchTypeID, string searchString, string currentFilter, int? pageIndex)
        {
            var b1RADIOContext = _context.Soundtrack.Include(s => s.Genre).Include(s => s.Singer);

            ViewData["CurrentSortOrder"] = String.IsNullOrEmpty(sortOrder) ? "genre_asc" : sortOrder;
            ViewData["CurrentFilter"] = searchString;

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            IQueryable<Soundtrack> soundtracks = from s in b1RADIOContext
                                                select s;

            if ((searchTypeID > 0) && (!String.IsNullOrEmpty(searchString)))
            {
                switch (searchTypeID)
                {
                    case 1:
                        soundtracks = soundtracks.Where(s => s.Genre.Name.Contains(searchString));
                        break;
                    case 2:
                        soundtracks = soundtracks.Where(s => s.Singer.Name.Contains(searchString));
                        break;
                    case 3:
                        soundtracks = soundtracks.Where(s => s.Title.Contains(searchString));
                        break;
                }
            }

            switch (sortOrder)
            {
                case "genre_desc":
                    soundtracks = soundtracks.OrderByDescending(s => s.Genre.Name);
                    break;
                case "singer_asc":
                    soundtracks = soundtracks.OrderBy(s => s.Singer.Name);
                    break;
                case "singer_desc":
                    soundtracks = soundtracks.OrderByDescending(s => s.Singer.Name);
                    break;
                case "title_asc":
                    soundtracks = soundtracks.OrderBy(s => s.Title);
                    break;
                case "title_desc":
                    soundtracks = soundtracks.OrderByDescending(s => s.Title);
                    break;
                default:
                    soundtracks = soundtracks.OrderBy(s => s.Genre.Name);
                    break;
            }

            int pageSize = 8;
            var soundtrackList = await PaginatedList<Soundtrack>.CreateAsync(soundtracks.AsNoTracking(), pageIndex ?? 1, pageSize);
            //var soundtrackList = await soundtracks.AsNoTracking().ToListAsync();
            return View(soundtrackList);
        }

        // GET: Soundtracks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soundtrack = await _context.Soundtrack
                .Include(s => s.Genre)
                .Include(s => s.Singer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (soundtrack == null)
            {
                return NotFound();
            }

            return View(soundtrack);
        }

        // GET: Soundtracks/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genre.OrderBy(e => e.Name), "Id", "Name");
            ViewData["SingerId"] = new SelectList(_context.Singer.OrderBy(e => e.Name), "Id", "Name");
            return View();
        }

        // POST: Soundtracks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, GenreId, SingerId, Title, ServerFilename, ClientFilename")] Soundtrack soundtrack)
        {
            if (ModelState.IsValid)
            {
                _context.Add(soundtrack);
                System.IO.File.Move(Path.Combine(TmpFileDir, soundtrack.ServerFilename), Path.Combine(WorkFileDir, soundtrack.ServerFilename));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genre.OrderBy(e => e.Name), "Id", "Name", soundtrack.GenreId);
            ViewData["SingerId"] = new SelectList(_context.Singer.OrderBy(e => e.Name), "Id", "Name", soundtrack.SingerId);
            
            return View(soundtrack);
        }

        // GET: Soundtracks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soundtrack = await _context.Soundtrack.FindAsync(id);
            if (soundtrack == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Genre.OrderBy(e => e.Name), "Id", "Name", soundtrack.GenreId);
            ViewData["SingerId"] = new SelectList(_context.Singer.OrderBy(e => e.Name), "Id", "Name", soundtrack.SingerId);
            return View(soundtrack);
        }

        // POST: Soundtracks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, GenreId, SingerId, Title, ServerFilename, ClientFilename")] Soundtrack soundtrack)
        {
            if (id != soundtrack.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Soundtrack existingSoundtrack = _context.Soundtrack.FirstOrDefault(e => e.Id == soundtrack.Id);
                _context.Entry<Soundtrack>(existingSoundtrack).State = EntityState.Detached;
                try
                {                    
                    _context.Update(soundtrack);
                    if (System.IO.File.Exists(Path.Combine(TmpFileDir, soundtrack.ServerFilename)))
                    {
                        if (existingSoundtrack != null)
                            System.IO.File.Delete(Path.Combine(WorkFileDir, existingSoundtrack.ServerFilename));
                        System.IO.File.Move(Path.Combine(TmpFileDir, soundtrack.ServerFilename), Path.Combine(WorkFileDir, soundtrack.ServerFilename));
                    }
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SoundtrackExists(soundtrack.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genre.OrderBy(e => e.Name), "Id", "Name", soundtrack.GenreId);
            ViewData["SingerId"] = new SelectList(_context.Singer.OrderBy(e => e.Name), "Id", "Name", soundtrack.SingerId);
            return View(soundtrack);
        }

        // GET: Soundtracks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soundtrack = await _context.Soundtrack
                .Include(s => s.Genre)
                .Include(s => s.Singer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (soundtrack == null)
            {
                return NotFound();
            }

            return View(soundtrack);
        }

        // POST: Soundtracks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var soundtrack = await _context.Soundtrack.FindAsync(id);
            _context.Soundtrack.Remove(soundtrack);

            var fileName = Path.Combine(WorkFileDir, soundtrack.ServerFilename);
            if (System.IO.File.Exists(fileName))
            {
                System.IO.File.Delete(fileName);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SoundtrackExists(int id)
        {
            return _context.Soundtrack.Any(e => e.Id == id);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult AddSinger()
        {
            var model = new Singer();

            return PartialView("_AddSingerPartial", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddSinger(Singer model)
        {

Sveyko.B1RADIO/Views/Soundtracks/Create.cshtml
@model Sveyko.B1RADIO.Models.Soundtrack

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Soundtrack</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SingerId" class="control-label"></label>
                <div class="input-group">
                    @*<select  id="dropDownSingerId" asp-for="SingerId" class="form-control" asp-items="ViewBag.SingerId"></select>*@
                    <select id="SingerId" asp-for="SingerId" name="SingerId" class="form-control"></select>                    
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-success" data-toggle="ajax-modal" data-target="#add-singer">
                            New
                        </button>
                    </span>
                </div>
                <span asp-validation-for="SingerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input id="TitleID" asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientFilename" class="control-label"></label>
                <div class="input-group">
                    <input asp-for="ClientFilename" id="ClientFilename" name="ClientFilename" type="text" class="form-control" readonly>
                    <input asp-for="ServerFilename" type="hidden" id="ServerFilename" value="" name="ServerFilename">
                    <span class="input-group-btn">
                        <label class="btn btn-default btn-file">
                            Browse <input id="fileUploadID" type="file" style="display: none;">
                        </label>
                    </span>
                </div>
                <span asp-validation-for="ClientFilename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="button" class="btn btn-default" value="To List" onclick="location.href='@Url.Action("Index", "Soundtracks")'" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

<div id="modal-placeholder"></div>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {             

            $(document).ready(function () {
                RefreshSingerList("", 0);
            });

        });
    </script>

}

Sveyko.B1RADIO/Views/Soundtracks/Delete.cshtml
@model Sveyko.B1RADIO.Models.Soundtrack

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<div>
    <h4>Soundtrack</h4>
    <div class="alert alert-danger">
        <h3>Are you sure you want to delete this soundtrack?</h3>
    </div>
    <hr />
    <row>
        <div class="col-12 col-sm-12 col-xs-12">
            <strong>
                @Html.DisplayNameFor(model => model.Genre)
            </strong><br>
        </div>
        <div class="col-12 col-sm-12 col-xs-12">
            @Html.DisplayFor(model => model.Genre.Name)
        </div>
    </row>
    <p>&nbsp;</p>
    <row>
        <div class="col-12 col-sm-12 col-xs-12">
            <strong>
                @Html.DisplayNameFor(model => model.Singer)
            </strong><br>
        </div>
        <div class="col-12 col-sm-12 col-xs-12">
            @Html.DisplayFor(model => model.Singer.Name)
        </div>
    </row>
    <p>&nbsp;</p>
    <row>
        <div class="col-12 col-sm-12 col-xs-12">
            <strong>
                @Html.DisplayNameFor(model => model.Title)
            </strong><br>
        </div>
        <div class="col-12 col-sm-12 col-xs-12">
            @Html.DisplayFor(model => model.Title)
        </div>
    </row>
    <p>&nbsp;</p>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        @*| <a asp-action="Index">Back to List</a>*@
        <input type="button" class="btn btn-default" value="To List" onclick="location.href='@Url.Action("Index", "Soundtracks")'" />
    </form>
</div>

Sveyko.B1RADIO/Views/Soundtracks/Details.cshtml
@model Sveyko.B1RADIO.Models.Soundtrack

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Soundtrack</h4>
    <hr />
    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ClientFilename)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ClientFilename)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Genre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Genre.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Singer)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Singer.Name)
            </dd>
        </dl>*@
    <row>
        <div class="col-12 col-sm-12 col-xs-12">
            <strong>
                @Html.DisplayNameFor(model => model.Genre)
            </strong><br>
        </div>
        <div class="col-12 col-sm-12 col-xs-12">
            @Html.DisplayFor(model => model.Genre.Name)
        </div>
    </row>
    <p>&nbsp;</p>
    <row>
        <div class="col-12 col-sm-12 col-xs-12">
            <strong>
                @Html.DisplayNameFor(model => model.Singer)
            </strong><br>
        </div>
        <div class="col-12 col-sm-12 col-xs-12">
            @Html.DisplayFor(model => model.Singer.Name)
        </div>
    </row>
    <p>&nbsp;</p>
    <row>
        <div class="col-12 col-sm-12 col-xs-12">
            <strong>
                @Html.DisplayNameFor(model => model.Title)
            </strong><br>
        </div>
        <div class="col-12 col-sm-12 col-xs-12">
            @Html.DisplayFor(model => model.Title)
        </div>
    </row>
    <p>&nbsp;</p>
    @{
        string fileName = "/soundtracks/" + @Model.ServerFilename;
    }
    <row>
        <div class="col-12 col-sm-12 col-xs-12">
            @if (!string.IsNullOrEmpty(fileName))
            {
                <audio controls>
                    <source src="@fileName" type="audio/mpeg">
                </audio>

                @*<a href="#" id="playAudio">Play Audio</a>
                    <a href="#" id="pauseAudio">Pause Audio</a>*@
                @*<audio id="audio">
                        <source src="@fileName" type="audio/mpeg">
                        Your browser doesn't support the audio element.
                    </audio>*@
            }
        </div>
    </row>
</div>
<p>&nbsp;</p>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>*@
    <input type="button" class="btn btn-primary" value="Edit" onclick="location.href='@Url.Action("Edit", "Soundtracks",new { id = @Model.Id })'" />
    <input type="button" class="btn btn-default" value="To List" onclick="location.href='@Url.Action("Index", "Soundtracks")'" />
</div>

<script>
    var el = document.getElementById("playAudio");
    el.onclick = playAudio;
    var elPause = document.getElementById("pauseAudio");
    elPause.onclick = pauseAudio;
    function playAudio() {
        document.getElementById("audio").play();
    }
    function pauseAudio() {
        document.getElementById("audio").pause();
    }
    //var el2 = document.getElementById("btnPlayID");
    //el2.onclick = test;
    //function test() {
    //    //playAudio();
    //    el2.find('span:first').toggleClass('glyphicon-log-in glyphicon-log-out');
    //   // var color = clicked ? 'red' : 'blue';
    //    //$(this).css('background-color', color);
    //    clicked = !clicked;
    //};
</script>

Sveyko.B1RADIO/Views/Soundtracks/Edit.cshtml
@model Sveyko.B1RADIO.Models.Soundtrack

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Soundtrack</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="SingerId" class="control-label"></label>
                    <select asp-for="SingerId" class="form-control" asp-items="ViewBag.SingerId"></select>
                    <span asp-validation-for="SingerId" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="SingerId" class="control-label"></label>
                <div class="input-group">
                    <select id="SingerId" asp-for="SingerId" name="SingerId" class="form-control"></select>                    
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-success" data-toggle="ajax-modal" data-target="#add-singer">
                            New
                        </button>
                    </span>
                </div>
                <span asp-validation-for="SingerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input id="TitleID" asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientFilename" class="control-label"></label>
                <div class="input-group">
                    <input asp-for="ClientFilename" id="ClientFilename" name="ClientFilename" type="text" class="form-control" readonly>
                    <input asp-for="ServerFilename" type="hidden" id="ServerFilename" name="ServerFilename">
                    <span class="input-group-btn">
                        <label class="btn btn-default btn-file">
                            Browse <input id="fileUploadID" type="file" style="display: none;">
                        </label>
                    </span>
                </div>
                <span asp-validation-for="ClientFilename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <input type="button" class="btn btn-default" value="To List" onclick="location.href='@Url.Action("Index", "Soundtracks")'" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>    
</div>*@

<div id="modal-placeholder"></div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {
            $(document).ready(function () {
                RefreshSingerList("", @Model.SingerId);
            });

        });
    </script>

}